version: '2'

services:
  squid:
    image: squid:latest
    build: ./
    restart: always
    ports:
      - 3128:3128
    # environment:
    #   - SQUID_PEERS=seth sleipnir
    volumes:
      - /srv/squid:/data
